### ISSUE TITLE
Problem in Container

### ISSUE THREAD

**Issue by matheusfterra** [MiniGlome/Tiktok-uploader#10]
Hi, I'm using  a Docker Container, and have this issue, someone can help me please?

![image](https://github.com/MiniGlome/Tiktok-uploader/assets/25447579/71ab9d65-2a0e-4dd0-8c12-4c96c12ceb24)

**Comment by insurgencless** [comment]
use chatgtp only advice i can give i know nothing about backend code

**Comment by lonardonifabio** [comment]
I've the same error and my project is blocked now.

`Moviepy - Building video video_finale.mp4.

MoviePy - Writing audio in video_finaleTEMP_MPY_wvf_snd.mp3

[2023-06-15 20:32:01.952298] MoviePy - Done.                          [2023-06-15 20:32:01.947918] 

Moviepy - Writing video video_finale.mp4


[2023-06-15 20:32:06.786054] 2023-06-15 20:32:06.785 Uncaught app exception69] 

Traceback (most recent call last):

  File "/home/appuser/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script

    exec(code, module.__dict__)

  File "/app/aihypernews/news.py", line 564, in <module>

    st.write("Posted on Tik Tok:", uploadVideo(session_id, file, title, tags, verbose=True))

  File "/app/aihypernews/Tiktok_uploader.py", line 75, in uploadVideo

    user_id = r.json()["data"]["user_id_str"]

KeyError: 'user_id_str`

Can someone please support us? ChatGPT is not enough :)
